import socket
import os
import sys
import time
import datetime
import webbrowser
os.system ('clear')
print (sys.version)
print ("")
print (webbrowser._browsers)
print (sys.copyright)
print ("")
print ("PlatForm:" + sys.platform)
print ("Pwd Script Batman, MakeByWaleed,PWD:")
print (sys.argv)
print ("#Waleed Gmxd waloodwaleedaa@gmail.com")
print ("Hello Login To Script")
print ("Passowrd Script :batman")
print ("...")
time.sleep (1)
print ("50%")
time.sleep (2)
print ("90%")
time.sleep (0.5)
print ("100%")
print ("هلا بجيش باطما")
print ("جيش باطمان")
print ("Now Time:")
print (datetime.datetime.now())
print ("")
print ("Year")
print (datetime.datetime.now().year)
print ("Month:")
print (datetime.datetime.now().month)
print ("Day:")
print (datetime.datetime.now().day)
print (time.time)
print ("Type User Name:")
user = input ("==> ")
print ("Type Passowrd Script:")
passs = input ("==> batman=%>")
if (passs == "batman"):
	print ("Hello To Script.:"+user)
	print ("")
	domenn = input ("%Type&Domen%==>")
	domen = socket.gethostbyname (domenn)
	print ("[||Domen:" + domenn + "Domen/||]")
	print ("[||IP:" + domen + "IP/]||")
else:
	print ("Erorr")
	print ("çøê")
